//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MuebleriaDBEntities : DbContext
    {
        public MuebleriaDBEntities()
            : base("name=MuebleriaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_CLIENTES> TBL_CLIENTES { get; set; }
        public DbSet<TBL_CUENTAS_X_PAGAR> TBL_CUENTAS_X_PAGAR { get; set; }
        public DbSet<TBL_DEUDORES> TBL_DEUDORES { get; set; }
        public DbSet<TBL_FACTURA_DETALLE> TBL_FACTURA_DETALLE { get; set; }
        public DbSet<TBL_FACTURAS> TBL_FACTURAS { get; set; }
        public DbSet<TBL_PRODUCTOS> TBL_PRODUCTOS { get; set; }
        public DbSet<TBL_SUPLIDORES> TBL_SUPLIDORES { get; set; }
        public DbSet<TBL_TIPOSUPLIDORES> TBL_TIPOSUPLIDORES { get; set; }
        public DbSet<TBL_USUARIOS> TBL_USUARIOS { get; set; }
    
        public virtual int ACTIVEUSER(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTIVEUSER", userIdParameter);
        }
    
        public virtual int INACTIVEUSER(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INACTIVEUSER", userIdParameter);
        }
    
        public virtual int PRODUCT_SOLD(string productID, Nullable<int> amount)
        {
            var productIDParameter = productID != null ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRODUCT_SOLD", productIDParameter, amountParameter);
        }
    
        public virtual ObjectResult<GET_BILLS_DETAILS_A_DAY_Result> GET_BILLS_DETAILS_A_DAY(Nullable<System.DateTime> dATE1)
        {
            var dATE1Parameter = dATE1.HasValue ?
                new ObjectParameter("DATE1", dATE1) :
                new ObjectParameter("DATE1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_BILLS_DETAILS_A_DAY_Result>("GET_BILLS_DETAILS_A_DAY", dATE1Parameter);
        }
    }
}
