//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPOSUPLIDORES
    {
        public TBL_TIPOSUPLIDORES()
        {
            this.TBL_SUPLIDORES = new HashSet<TBL_SUPLIDORES>();
        }
    
        public int TipoID { get; set; }
        public string NombreTipo { get; set; }
    
        public virtual ICollection<TBL_SUPLIDORES> TBL_SUPLIDORES { get; set; }
    }
}
