//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTES
    {
        public TBL_CLIENTES()
        {
            this.TBL_FACTURAS = new HashSet<TBL_FACTURAS>();
        }
    
        public string CedulaCliente { get; set; }
        public string RNC { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<TBL_FACTURAS> TBL_FACTURAS { get; set; }
    }
}
