//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIOS
    {
        public TBL_USUARIOS()
        {
            this.TBL_FACTURAS = new HashSet<TBL_FACTURAS>();
        }
    
        public int UsuarioID { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int ActivoAhora { get; set; }
    
        public virtual ICollection<TBL_FACTURAS> TBL_FACTURAS { get; set; }
    }
}
