//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTOS
    {
        public int ProductoID { get; set; }
        public string CodigoDeBarra { get; set; }
        public int SuplidorID { get; set; }
        public string ProductoNombre { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioPorUnidad { get; set; }
        public int UnidadesEnAlmacen { get; set; }
        public int Descontinuado { get; set; }
        public string Marca { get; set; }
        public System.DateTime FechaDeIngreso { get; set; }
        public string SuplidorNombre { get; set; }
        public decimal PrecioDeLista { get; set; }
        public Nullable<System.DateTime> FechaDeCompra { get; set; }
    
        public virtual TBL_SUPLIDORES TBL_SUPLIDORES { get; set; }
    }
}
