//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FACTURAS
    {
        public TBL_FACTURAS()
        {
            this.TBL_FACTURA_DETALLE = new HashSet<TBL_FACTURA_DETALLE>();
        }
    
        public int FacturaID { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public decimal TotalEnFactura { get; set; }
        public string CedulaCliente { get; set; }
        public int UsuarioID { get; set; }
        public string NombreCliente { get; set; }
        public string NombreUsuario { get; set; }
    
        public virtual TBL_CLIENTES TBL_CLIENTES { get; set; }
        public virtual ICollection<TBL_FACTURA_DETALLE> TBL_FACTURA_DETALLE { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
