//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEUDORES
    {
        public TBL_DEUDORES()
        {
            this.TBL_CUENTAS_X_PAGAR = new HashSet<TBL_CUENTAS_X_PAGAR>();
        }
    
        public int DeudorID { get; set; }
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string NombreContacto { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<TBL_CUENTAS_X_PAGAR> TBL_CUENTAS_X_PAGAR { get; set; }
    }
}
